// Auto-generated by stig - test runner entry point
// This file should be compiled with all test_*.cpp files

#define STIG_TEST_MAIN
#include "stig_test.h"

int main(int argc, char** argv) {
    (void)argc;
    (void)argv;
    return stig::test::run_all();
}
