// =============================================================================
// stig_test.h - Single-header C++ test framework
// Auto-generated by stig - https://github.com/your-repo/stig
// =============================================================================
//
// Usage:
//   #include "stig_test.h"
//
//   STIG_TEST(test_name) {
//       STIG_CHECK(condition);
//       STIG_CHECK_EQ(a, b);
//       STIG_REQUIRE(must_be_true);
//   }
//
// =============================================================================

#ifndef STIG_TEST_H
#define STIG_TEST_H

#include <iostream>
#include <vector>
#include <string>
#include <functional>
#include <cstring>
#include <exception>
#include <sstream>

namespace stig {
namespace test {

// =============================================================================
// Test Registration
// =============================================================================

struct TestCase {
    const char* name;
    const char* file;
    int line;
    std::function<void()> func;
};

inline std::vector<TestCase>& registry() {
    static std::vector<TestCase> tests;
    return tests;
}

struct TestRegistrar {
    TestRegistrar(const char* name, const char* file, int line, std::function<void()> func) {
        registry().push_back({name, file, line, func});
    }
};

// =============================================================================
// Test Context (tracks assertions and failures)
// =============================================================================

struct Context {
    int assertions = 0;
    int failures = 0;
    const char* current_test = nullptr;
    const char* current_file = nullptr;
    int current_line = 0;
};

inline Context& ctx() {
    static Context c;
    return c;
}

// =============================================================================
// Reporting
// =============================================================================

inline void report_failure(const char* expr, const char* file, int line) {
    std::cerr << file << ":" << line << ": FAILED: " << expr << "\n";
    ctx().failures++;
}

inline void report_failure_with_values(const char* expr, const char* file, int line,
                                        const std::string& lhs, const std::string& rhs) {
    std::cerr << file << ":" << line << ": FAILED: " << expr << "\n";
    std::cerr << "  Left:  " << lhs << "\n";
    std::cerr << "  Right: " << rhs << "\n";
    ctx().failures++;
}

inline void report_success() {
    ctx().assertions++;
}

// =============================================================================
// Value to string conversion
// =============================================================================

template<typename T>
inline std::string to_string(const T& value) {
    std::ostringstream oss;
    oss << value;
    return oss.str();
}

// Specialization for bool
template<>
inline std::string to_string(const bool& value) {
    return value ? "true" : "false";
}

// Specialization for nullptr
inline std::string to_string(std::nullptr_t) {
    return "nullptr";
}

// =============================================================================
// Test Runner
// =============================================================================

inline int run_all() {
    int failed = 0;
    int passed = 0;
    
    std::cout << "Running " << registry().size() << " test(s)...\n\n";
    
    for (auto& tc : registry()) {
        ctx().current_test = tc.name;
        ctx().current_file = tc.file;
        ctx().current_line = tc.line;
        ctx().assertions = 0;
        ctx().failures = 0;
        
        std::cout << "[ RUN      ] " << tc.name << "\n";
        
        try {
            tc.func();
        } catch (const std::exception& e) {
            std::cerr << tc.file << ":" << tc.line << ": EXCEPTION: " << e.what() << "\n";
            ctx().failures++;
        } catch (...) {
            std::cerr << tc.file << ":" << tc.line << ": UNKNOWN EXCEPTION\n";
            ctx().failures++;
        }
        
        if (ctx().failures > 0) {
            failed++;
            std::cout << "[  FAILED  ] " << tc.name << " (" << ctx().failures << " failure(s))\n";
        } else {
            passed++;
            std::cout << "[       OK ] " << tc.name << " (" << ctx().assertions << " assertion(s))\n";
        }
    }
    
    std::cout << "\n";
    std::cout << "==========================================================\n";
    std::cout << "Total: " << registry().size() << " test(s)\n";
    std::cout << "Passed: " << passed << "\n";
    std::cout << "Failed: " << failed << "\n";
    std::cout << "==========================================================\n";
    
    return failed > 0 ? 1 : 0;
}

} // namespace test
} // namespace stig

// =============================================================================
// MACROS
// =============================================================================

// Define a test case
#define STIG_TEST(name) \
    static void stig_test_##name(); \
    static stig::test::TestRegistrar stig_reg_##name(#name, __FILE__, __LINE__, stig_test_##name); \
    static void stig_test_##name()

// Basic check - continues on failure
#define STIG_CHECK(expr) \
    do { \
        if (!(expr)) { \
            stig::test::report_failure(#expr, __FILE__, __LINE__); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

// Require - stops test on failure
#define STIG_REQUIRE(expr) \
    do { \
        if (!(expr)) { \
            stig::test::report_failure(#expr, __FILE__, __LINE__); \
            return; \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

// Comparison checks with value reporting
#define STIG_CHECK_EQ(a, b) \
    do { \
        auto _stig_a = (a); \
        auto _stig_b = (b); \
        if (!(_stig_a == _stig_b)) { \
            stig::test::report_failure_with_values(#a " == " #b, __FILE__, __LINE__, \
                stig::test::to_string(_stig_a), stig::test::to_string(_stig_b)); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_CHECK_NE(a, b) \
    do { \
        auto _stig_a = (a); \
        auto _stig_b = (b); \
        if (!(_stig_a != _stig_b)) { \
            stig::test::report_failure_with_values(#a " != " #b, __FILE__, __LINE__, \
                stig::test::to_string(_stig_a), stig::test::to_string(_stig_b)); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_CHECK_LT(a, b) \
    do { \
        auto _stig_a = (a); \
        auto _stig_b = (b); \
        if (!(_stig_a < _stig_b)) { \
            stig::test::report_failure_with_values(#a " < " #b, __FILE__, __LINE__, \
                stig::test::to_string(_stig_a), stig::test::to_string(_stig_b)); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_CHECK_LE(a, b) \
    do { \
        auto _stig_a = (a); \
        auto _stig_b = (b); \
        if (!(_stig_a <= _stig_b)) { \
            stig::test::report_failure_with_values(#a " <= " #b, __FILE__, __LINE__, \
                stig::test::to_string(_stig_a), stig::test::to_string(_stig_b)); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_CHECK_GT(a, b) \
    do { \
        auto _stig_a = (a); \
        auto _stig_b = (b); \
        if (!(_stig_a > _stig_b)) { \
            stig::test::report_failure_with_values(#a " > " #b, __FILE__, __LINE__, \
                stig::test::to_string(_stig_a), stig::test::to_string(_stig_b)); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_CHECK_GE(a, b) \
    do { \
        auto _stig_a = (a); \
        auto _stig_b = (b); \
        if (!(_stig_a >= _stig_b)) { \
            stig::test::report_failure_with_values(#a " >= " #b, __FILE__, __LINE__, \
                stig::test::to_string(_stig_a), stig::test::to_string(_stig_b)); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

// Require variants (stop on failure)
#define STIG_REQUIRE_EQ(a, b) \
    do { \
        auto _stig_a = (a); \
        auto _stig_b = (b); \
        if (!(_stig_a == _stig_b)) { \
            stig::test::report_failure_with_values(#a " == " #b, __FILE__, __LINE__, \
                stig::test::to_string(_stig_a), stig::test::to_string(_stig_b)); \
            return; \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_REQUIRE_NE(a, b) \
    do { \
        auto _stig_a = (a); \
        auto _stig_b = (b); \
        if (!(_stig_a != _stig_b)) { \
            stig::test::report_failure_with_values(#a " != " #b, __FILE__, __LINE__, \
                stig::test::to_string(_stig_a), stig::test::to_string(_stig_b)); \
            return; \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

// Exception testing
#define STIG_CHECK_THROWS(expr) \
    do { \
        bool _stig_threw = false; \
        try { expr; } catch (...) { _stig_threw = true; } \
        if (!_stig_threw) { \
            stig::test::report_failure(#expr " should throw", __FILE__, __LINE__); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_CHECK_NOTHROW(expr) \
    do { \
        bool _stig_threw = false; \
        try { expr; } catch (...) { _stig_threw = true; } \
        if (_stig_threw) { \
            stig::test::report_failure(#expr " should not throw", __FILE__, __LINE__); \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_REQUIRE_THROWS(expr) \
    do { \
        bool _stig_threw = false; \
        try { expr; } catch (...) { _stig_threw = true; } \
        if (!_stig_threw) { \
            stig::test::report_failure(#expr " should throw", __FILE__, __LINE__); \
            return; \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#define STIG_REQUIRE_NOTHROW(expr) \
    do { \
        bool _stig_threw = false; \
        try { expr; } catch (...) { _stig_threw = true; } \
        if (_stig_threw) { \
            stig::test::report_failure(#expr " should not throw", __FILE__, __LINE__); \
            return; \
        } else { \
            stig::test::report_success(); \
        } \
    } while(0)

#endif // STIG_TEST_H
